### PR TITLE
tuple_io + tuple_cat

### PR DESCRIPTION
**Pull request by andrewcorrigan**
Getting the ball rolling on this pull request.  There are two pieces:
1. tuple_io, which is a minimal modification of code from [1] to enable stream support for thrust::tuple.  Documentation of this functionality is provided in [2]
2. tuple_cat.  I am including code from @bryancatanzaro [3], as per the request of @jaredhoberock in the thrust-users discussion [4].

[1] https://github.com/boostorg/tuple
[2] http://www.boost.org/doc/libs/1_55_0/libs/tuple/doc/tuple_users_guide.html#streaming
[3] https://github.com/bryancatanzaro/tuple-cat 
[4] https://groups.google.com/d/msg/thrust-users/NxMTkwPp2bg/-s79wXylAREJ

### CODE REVIEW

**Comment by andrewcorrigan** [comment]
unit tests are added.

I had to compile the unit tests manually..  I tried with scons, using the latest upstream revision, but even after bypassing many errors, I couldn't get it to work.  Is it supposed to work on mac 10.10 + cuda 7?

**Comment by andrewcorrigan** [comment]
I'm really sorry that I took forever to get this finished.  Are you still interested in this PR?  If there's anything I can do to help, please let me know.

**Comment by brycelelbach** [comment]
This was closed when we pushed the new Git master history to GitHub. Please rebase onto the new master and we'll take a look.

**Comment by brycelelbach** [comment]
So we're just gonna replace our tuple with a C++11 tuple or `cuda::std::tuple`, so I don't think this will make sense going forward.

**Comment by andrewcorrigan** [comment]
@brycelelbach  Great to hear there may be some progress on that front.  Will there be streaming/IO support using either of those tuple implementations (which I proposed to add via this PR)?

**Comment by brycelelbach** [comment]
Hey Andrew! Not at first, but we'll be open to PRs for that - if you want to rebase this onto top of trunk and reopen it we will be happy to merge it as is.

**Pull request closed without merging**
