### PR TITLE
Update to top of trunk CUB (1.8.x)

### PR DESCRIPTION
**Pull request by brycelelbach**

### CODE REVIEW

**Comment by brycelelbach** [comment]
@jaredhoberock can you help us review this?

**Comment by jaredhoberock** [comment]
@brycelelbach Any particular aspect of the changes that you'd like feedback on?

**Comment by brycelelbach** [comment]
Michal mentioned some amount of this was over his head, as he's not a CUDA device code expert. We are trying to get more rigourous about code reviews, so I'd appreciate if you could just look over and see if anything jumps out at you.

**Comment by jaredhoberock** [comment]
I'm in the same boat with Michal :-) If these changes came from Duane, I would trust them.

How were the changes created? Simply by slurping in from CUB top-of-tree?

**Pull request closed without merging**
