### PR TITLE
Optimize cuda_cub::__copy::device_to_device for contiguous trivial copies.

### PR DESCRIPTION
**Pull request by allisonvacanti**
This was code path was routing all copies, trivial or not, through `transform` with an identity functor.

Now, do a static check for whether the copy is trivial (iterators are contiguous and values are trivially copyable) and use `thrust::cuda_cub::trivial_copy_device_to_device` when possible.

Shelve 28136272

### CODE REVIEW

**Comment by griwes** [comment]
Is this logic consistent with the logic of `thrust::async::copy`?

**Comment by brycelelbach** [comment]
@allisonvacanti is this good to go?

**Comment by allisonvacanti** [comment]
This is pretty old and neglected at this point. It's low priority, so I was planning to wait until CI was stable before returning to it.

**Comment by allisonvacanti** [comment]
Doesn't build after rebase anymore, marking as draft until I can fix it.

**Comment by allisonvacanti** [comment]
Closing this for now as it is stale and low priority. I'll come back to it at some point.

**Pull request closed without merging**
