### PR TITLE
Fix C4244 from MSVC in sort.

### PR DESCRIPTION
**Pull request by zhihaoy**

### CODE REVIEW

**Comment by zhihaoy** [comment]
The issue goes away in MSVC 19.16.27030.1, should I leave this P/R open?

**Comment by brycelelbach** [comment]
@zhihaoy, hrm, your call. This probably isn't the right fix; instead of casting, we should change the type of the variable. @griwes, thoughts?

**Comment by zhihaoy** [comment]
It's a safe fix because "log2 round to integer" can't overflow any type.  Raising `num_passes` to `Size` looks pedantic... I will leave it open for a while because someone else seems to encounter the same issue https://devtalk.nvidia.com/default/topic/1064002/b/t/post/5387873/

**Comment by allisonvacanti** [comment]
This patch looks reasonable to me -- we wouldn't be running more than 2^32 passes so just casting to an `int` should be ok. @brycelelbach @griwes if you have any objections to this let me know, but I'll start moving towards integrating this in case folks are still using older MSVC 2017 builds.

**Comment by allisonvacanti** [comment]
Started internal CI: 28483968

**Comment by allisonvacanti** [comment]
Tests pass -- I'll merge this soon.

**Pull request merged**
