### PR TITLE
use c++11 auto for iterator types

### PR DESCRIPTION
**Pull request by rongou**
Seems to make the examples cleaner. :)

### CODE REVIEW

**Comment by brycelelbach** [comment]
Running internal CI, but that has coverage gaps for C++11.

@griwes and @jaredhoberock to code review.

**Comment by brycelelbach** [comment]
Doing this without a version check is problematic, as we still have to support C++03. I'm not sure that we can take this as-is.

**Comment by jaredhoberock** [comment]
Once the example programs can use `auto` without introducing other problems, then I think that's a good idea.

The problem I see is that we'd need to communicate to the user somehow that their compiler needs to be set to a C++ dialect that includes `auto`. The example programs are intended to be pedagogical, and understandable by novice users that might not even be that familiar with C++. I worry that adding that additional an detail concerning dialect would present an obstacle to new learners.

**Comment by brycelelbach** [comment]
So, unfortunately, I think until we can move all of Thrust to be C++11 only, this will only complicate the examples; either we make all of these examples C++11 only, or we add `#ifdef`s to the examples, which makes them harder to read.

So, for now, let's shelve this.

**Comment by brycelelbach** [comment]
But thanks so much for the PR - we'll revisit this when we move to C++11 only.

**Comment by henryiii** [comment]
I'm still not convinced there are that many users eagerly upgrading to the latest cutting edge Thrust that are also still stuck on C++98...

**Pull request closed without merging**
