### PR TITLE
fix window warnings

### PR DESCRIPTION
**Pull request by egaburov**

### CODE REVIEW

**Comment by jaredhoberock** [comment]
If you look at the diff, it looks like your change touched every line in these files. Probably what happened is that Windows introduced new line endings or whitespace.

Could you resubmit your change such that the diff is limited to the edits of interest?

**Comment by egaburov** [comment]
Looks correct now.

**Comment by jaredhoberock** [comment]
Thanks Evgehnii, looks good to me. Since these changes are in the Bulk library, we need to keep them in sync. Could you submit a corresponding pull request here:

https://github.com/jaredhoberock/bulk

I'll merge both at the same time.

**Comment by egaburov** [comment]
Done.

**Pull request merged**
