### PR TITLE
thrust_exec_check_disable

### PR DESCRIPTION
**Pull request by andrewcorrigan**
Just like #570.

### CODE REVIEW

**Comment by jaredhoberock** [comment]
Looks fine to me. The annotation is required because `.construct()` may be a `__host__` function.

**Comment by egaburov** [comment]
Looks OK. One followup question though: is it because `.construct()` may come from host STL allocators, that are unannotated with `__host__ __device__`?

**Comment by andrewcorrigan** [comment]
I didn't pay too much attention to the details of the error messages in this instance, but last time [1] it was:

> storing a type with `__device__ __host__` constructor in a `thrust::host_vector`, which invokes the constructor from `__host__` code.

[1] https://github.com/thrust/thrust/issues/556#issuecomment-59660454

**Comment by jaredhoberock** [comment]
@egaburov : Yes, that's correct.

**Pull request merged**
