### PR TITLE
multi_permutation_iterator (sorry for the dupe)

### PR DESCRIPTION
**Pull request by andrewcorrigan**
multi_permutation_iterator resolves issue 70 [1], which was opened based on a request [2] I made over two years ago.

This iterator is general purpose, but is of particular significance due to its application in efficiently implementing stencil operations and multi-dimensional arrays, both of which are areas in which Thrust is currently lacking.

If a proliferation of new iterators is to be avoided then perhaps the functionality provided by multi_permutation_iterator could be integrated into permutation_iterator, to directly generalize permutation_iterators present capabilities? As it stands they have analogous functionality, both index into another iterator. Their difference only lies in the types of indexes allowed: in the case of permutation iterator only types such as int can be used as indexes and therefore permutation_iterator dereferences to produces a single value, whereas multi_permutation_iterator allows for tuples to be used as input and therefore dereferences to produce multiple values.

[1] thrust/thrust#70
[2] https://groups.google.com/d/msg/thrust-users/125vfWIGeQ4/LnTFRUu4eTwJ

PS: My apologies for the duplicate pull request.  I accidentally closed the previous one, and couldn't figure out how to re-open it.

### CODE REVIEW

**Comment by brycelelbach** [comment]
Andrew,

Can't merge this without tests. Are you willing to write some?

**Comment by andrewcorrigan** [comment]
Yes.  But, would you be willing to wait until July?   I'm pretty booked up until then.

**Comment by brycelelbach** [comment]
Dude, you should see my backlog :). And yah, that's no problem - take your time. I probably won't circle back to this until late July.

**Comment by brycelelbach** [comment]
This was closed when we pushed the new Git master history to GitHub. Please rebase onto the new master and we'll take a look.

**Comment by allisonvacanti** [comment]
@andrewcorrigan Any updates? It looks like this will need tests and a rebase before we can proceed with it.

I'm going to close this PR for now since it appears abandoned -- please reopen once it is ready to be re-reviewed.

**Comment by andrewcorrigan** [comment]
> @andrewcorrigan <https://github.com/andrewcorrigan> Any updates? It looks
> like this will need tests and a rebase before we can proceed with it.
>
no updates.  I don’t think it’s necessary to merge this into Thrust unless
there are other users who want it.

>

**Pull request closed without merging**
