### PR TITLE
Make `execute_on_stream` inherit from `dependencies_aware_execution_policy` 

### PR DESCRIPTION
**Pull request by brycelelbach**
This is a short-term fix, long-term some major restructuring is needed.

### CODE REVIEW

**Comment by allisonvacanti** [comment]
LGTM -- Have you run this through DVS?

**Comment by allisonvacanti** [comment]
Actually, we should probably add at least one test for this use case. I'm assuming this is for issue #1195?

**Comment by brycelelbach** [comment]
Yah agreed we need a test for this.

**Comment by brycelelbach** [comment]
So this doesn't actually work as intended. The longer term solution may be needed instead.

**Comment by brycelelbach** [comment]
Superseded by #1230

**Pull request closed without merging**
